CREATE SCHEMA IF NOT EXISTS ex7_cadastro;
CREATE SCHEMA IF NOT EXISTS ex7_academico;
CREATE SCHEMA IF NOT EXISTS ex7_avaliacao;
CREATE SCHEMA IF NOT EXISTS ex7_helpers;
CREATE SCHEMA IF NOT EXISTS ex7_trigger;