CREATE ROLE admin WITH 
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT
    NOLOGIN
    NOREPLICATION
    NOBYPASSRLS
    CONNECTION LIMIT 0
    PASSWORD NULL
    VALID UNTIL 'infinity'
;
CREATE ROLE manager;
CREATE ROLE operator;