CREATE SCHEMA IF NOT EXISTS exercicio1;
REVOKE ALL ON SCHEMA exercicio1 FROM PUBLIC;

CREATE TABLE IF NOT EXISTS usuario (
    id INT PRIMARY KEY,
    nome VARCHAR(40) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    senha VARCHAR(40) NOT NULL
);

